applications/cart/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from applications.orders import views as order_views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart-page'),
    path('update/', views.cart_update, name='update'),
    path('checkout/', order_views.checkout_page, name='checkout'),
]

applications/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.product_list, name='product-list'),
    path('cbv/', views.ProductList.as_view(), name='product-list-cbv'),
    path('cbv/<str:slug>/', views.ProductSlugDetail.as_view(), name='product-slug-detail-cbv'),
    path('<int:id>/', views.product_detail, name='product-detail'),
    path('<int:pk>/cbv/', views.ProductDetail.as_view(), name='product-detail-cbv'),
    path('create/', views.create_product, name='create_product'),
    path('create_product/', views.create_product_test, name='create_product_test'),
    path('update/<int:id>/', views.update_product, name='update_product'),
    path('update_product/<int:id>/', views.update_product_test, name='update_product_test'),
    path('delete/<int:id>/', views.delete_product, name='delete_product'),
    path('delete_product/<int:id>/', views.delete_product_test, name='delete_product_test'),
]

supermarket/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from applications.accounts.views import (
    LoginView,
    MyLogoutView,
    RegisterView,
    guest_email_view,
)
from .views import (
    main_page,
    contacts,
    learn_bootstrap,
)

from applications.orders.views import success_page_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    path('', main_page, name='main-page'),
    path('api/', include('applications.api.urls')),
    path('products/', include('applications.products.urls')),
    path('search/', include('applications.search.urls')),
    path('cart/', include('applications.cart.urls')),
    path('addresses/', include('applications.addresses.urls')),
    path('contacts/', contacts, name='contacts'),
    path('login/', LoginView.as_view(), name='login-page'),
    # path('logout/', logout_page, name='logout-page'),
    path('logout/', MyLogoutView.as_view(), name='logout-page'),
    path('register/', RegisterView.as_view(), name='register-page'),
    path('register/email/', guest_email_view, name='guest-email-view'),
    path('learn_bs/', learn_bootstrap, name='learn-bootstrap'),
    path('success_page/', success_page_view, name='success-page')
)


# urlpatterns = [
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('admin/', admin.site.urls),
#     path('', main_page, name='main-page'),
#     path('api/', include('applications.api.urls')),
#     path('products/', include('applications.products.urls')),
#     path('search/', include('applications.search.urls')),
#     path('cart/', include('applications.cart.urls')),
#     path('addresses/', include('applications.addresses.urls')),
#     path('contacts/', contacts, name='contacts'),
#     path('login/', LoginView.as_view(), name='login-page'),
#     # path('logout/', logout_page, name='logout-page'),
#     path('logout/', MyLogoutView.as_view(), name='logout-page'),
#     path('register/', RegisterView.as_view(), name='register-page'),
#     path('register/email/', guest_email_view, name='guest-email-view'),
#     path('learn_bs/', learn_bootstrap, name='learn-bootstrap'),
#     path('success_page/', success_page_view, name='success-page')
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/cart/models.py
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import pre_save, m2m_changed

from applications.products.models import Product

User = get_user_model()


class CartManager(models.Manager):
    def get_or_new(self, request):
        new = False
        cart_id = request.session.get('cart_id', None)  # get data from session
        qs = self.get_queryset().filter(id=cart_id, status='op')
        if qs.count() == 1:
            cart_obj = qs.first()
            if request.user.is_authenticated and not cart_obj.user:
                cart_obj.user = request.user
                cart_obj.save()
            print('Cart object has been founded')
        else:
            cart_obj = self.new(user=request.user)
            new = True
            request.session['cart_id'] = cart_obj.id
            print('Cart has been created')
        return cart_obj, new

    def new(self, user=None):
        user_obj = None
        if user and user.is_authenticated:
            user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    OPENED = 'op'
    CLOSED = 'cl'
    STATUS_CHOICES = (
        (OPENED, 'Opened'),
        (CLOSED, 'Closed'),
    )
    user = models.ForeignKey(User, blank=True, null=True, related_name='carts', on_delete=models.SET_NULL)
    products = models.ManyToManyField(Product, blank=True, related_name='carts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    subtotal = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    total = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=OPENED)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

    def close(self):
        self.status = 'cl'
        self.save(update_fields=['status'])


def cart_total_m2m_receiver(sender, instance, action, *args, **kwargs):
    if action in ['post_add', 'post_remove', 'post_clear']:
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(
    cart_total_m2m_receiver,
    sender=Cart.products.through
)

def total_price_pre_save_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal != 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08)
    else:
        instance.total = 0

pre_save.connect(
    total_price_pre_save_receiver,
    sender=Cart
)

applications/cart/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from applications.cart.models import Cart
from applications.products.models import Product


def cart_view(request):
    cart_obj, new = Cart.objects.get_or_new(request)
    return render(request, 'cart/cart_page.html', locals())


@require_POST
def cart_update(request):
    cart_obj, is_new = Cart.objects.get_or_new(request)
    product_id = request.POST.get('product_id')
    qs = Product.objects.filter(id=product_id)
    if qs.count() == 1:
        product_obj = qs.first()
        if product_obj not in cart_obj.products.all():
            cart_obj.products.add(product_obj)
        else:
            cart_obj.products.remove(product_obj)
        request.session['cart_items'] = cart_obj.products.count()
    return redirect('cart:cart-page')



# request.session.set_expiry(300) # 5 min
# print(request.session)
# print(dir(request.session))
# request.session['id'] = 10 # set data in session
# del request.session['id'] # delete data by key from session

templates/cart/cart_page.html
{% extends 'base.html' %}
{% load custom_tags %}
{% load i18n %}

{% block content %}
{#      <div class="container">#}
{#      <div class="row">#}
{#        <div class="col-12" class="d-block mx-auto text-center">#}
{#          {% for category in categories_list %}#}
{#              {{ category.title }}#}
{#          {% empty %}#}
{#              No categories#}
{#          {% endfor %}#}
{#                  <form method="post" action="{% url 'products:create_product' %}">#}
{#            {% csrf_token %}#}
{#                    {{ form.as_p }}#}
{#                    <table class="table">#}
{#                        {{ formset.management_form }}#}
{#                        {{ formset.non_form_errors }}#}
{#                        {% for form in formset.forms %}#}
{#                            {% if forloop.first %}#}
{#                                <thead>#}
{#                                <tr>#}
{#                                    {% for field in form.visible_fields %}#}
{#                                        <th>{{ field.label|capfirst }}</th>#}
{#                                    {% endfor %}#}
{#                                </tr>#}
{#                                </thead>#}
{#                            {% endif %}#}
{#                            <tr class="formset_row">#}
{#                                {% for field in form.visible_fields %}#}
{#                                    <td>#}
{#                                    {% if forloop.first %}#}
{#                                        {% for hidden in form.hidden_fields %}#}
{#                                            {{ hidden }}#}
{#                                        {% endfor %}#}
{#                                    {% endif %}#}
{##}
{#                                    {{ field.errors.as_ul }}#}
{#                                    {{ field }}#}
{#                                    </td>#}
{#                                {% endfor %}#}
{#                            </tr>#}
{#                        {% endfor %}#}
{#                    </table>#}
{#            <button type="submit" class="btn btn-success">Submit</button>#}
{#          </form>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}

  <div class="container py-5">
    <div class="row">
      <div class="col-12 d-block mx-auto text-center">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">{% trans "Product name" %}</th>
              <th scope="col">Price</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for product in cart_obj.products.all %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ product.get_absolute_url }}">
                  {{ product.title|lower_string }}</a></td>
                <td>{{ product.price }}</td>
                <td>
                  {% include 'snippets/cart-update.html' with product=product in_cart=True %}
                </td>
              </tr>
            {% endfor %}
            <tr>
              <th colspan="2" class="text-right">Subtotal:</th>
              <th>{{ cart_obj.subtotal }}
                <svg height="20px" viewBox="0 0 512 512" width="20px" xmlns="http://www.w3.org/2000/svg"><path d="m256 151c23.863281 0 45.457031 14.132812 55.015625 36.007812l27.488281-12.015624c-14.332031-32.796876-46.714844-53.992188-82.503906-53.992188-49.625 0-90 40.375-90 90s40.375 90 90 90c35.789062 0 68.171875-21.195312 82.503906-53.992188l-27.488281-12.015624c-9.558594 21.875-31.152344 36.007812-55.015625 36.007812-33.085938 0-60-26.914062-60-60s26.914062-60 60-60zm0 0"/><path d="m181 331h150v30h-150zm0 0"/><path d="m256 0c-140.960938 0-256 115.050781-256 256 0 140.960938 115.050781 256 256 256 140.960938 0 256-115.050781 256-256 0-140.960938-115.050781-256-256-256zm0 482c-124.617188 0-226-101.382812-226-226s101.382812-226 226-226 226 101.382812 226 226-101.382812 226-226 226zm0 0"/><path d="m256 61c-107.523438 0-195 87.476562-195 195s87.476562 195 195 195 195-87.476562 195-195-87.476562-195-195-195zm0 360c-90.980469 0-165-74.019531-165-165s74.019531-165 165-165 165 74.019531 165 165-74.019531 165-165 165zm0 0"/></svg>
              </th>
            </tr>
            <tr>
              <th colspan="2" class="text-right">Total:</th>
              <th>{{ cart_obj.total }}
                <svg height="20px" viewBox="0 0 512 512" width="20px" xmlns="http://www.w3.org/2000/svg"><path d="m256 151c23.863281 0 45.457031 14.132812 55.015625 36.007812l27.488281-12.015624c-14.332031-32.796876-46.714844-53.992188-82.503906-53.992188-49.625 0-90 40.375-90 90s40.375 90 90 90c35.789062 0 68.171875-21.195312 82.503906-53.992188l-27.488281-12.015624c-9.558594 21.875-31.152344 36.007812-55.015625 36.007812-33.085938 0-60-26.914062-60-60s26.914062-60 60-60zm0 0"/><path d="m181 331h150v30h-150zm0 0"/><path d="m256 0c-140.960938 0-256 115.050781-256 256 0 140.960938 115.050781 256 256 256 140.960938 0 256-115.050781 256-256 0-140.960938-115.050781-256-256-256zm0 482c-124.617188 0-226-101.382812-226-226s101.382812-226 226-226 226 101.382812 226 226-101.382812 226-226 226zm0 0"/><path d="m256 61c-107.523438 0-195 87.476562-195 195s87.476562 195 195 195 195-87.476562 195-195-87.476562-195-195-195zm0 360c-90.980469 0-165-74.019531-165-165s74.019531-165 165-165 165 74.019531 165 165-74.019531 165-165 165zm0 0"/></svg>
              </th>
            </tr>
          </tbody>
        </table>
        <div class="col-md-5 d-block mx-auto text-center">
          <a href="{% url 'cart:checkout' %}" class="btn btn-block btn-success">Оформить заказ</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}