applications/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.product_list, name='product-list'),
    path('cbv/', views.ProductList.as_view(), name='product-list-cbv'),
    path('cbv/<str:slug>/', views.ProductSlugDetail.as_view(), name='product-slug-detail-cbv'),
    path('<int:id>/', views.product_detail, name='product-detail'),
    path('<int:pk>/cbv/', views.ProductDetail.as_view(), name='product-detail-cbv'),
    path('create/', views.create_product, name='create_product'),
    path('create_product/', views.create_product_test, name='create_product_test'),
    path('update/<int:id>/', views.update_product, name='update_product'),
    path('update_product/<int:id>/', views.update_product_test, name='update_product_test'),
    path('delete/<int:id>/', views.delete_product, name='delete_product'),
    path('delete_product/<int:id>/', views.delete_product_test, name='delete_product_test'),
]

supermarket/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from applications.accounts.views import (
    LoginView,
    MyLogoutView,
    RegisterView,
    guest_email_view,
)
from .views import (
    main_page,
    contacts,
    learn_bootstrap,
)

from applications.orders.views import success_page_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    path('', main_page, name='main-page'),
    path('api/', include('applications.api.urls')),
    path('products/', include('applications.products.urls')),
    path('search/', include('applications.search.urls')),
    path('cart/', include('applications.cart.urls')),
    path('addresses/', include('applications.addresses.urls')),
    path('contacts/', contacts, name='contacts'),
    path('login/', LoginView.as_view(), name='login-page'),
    # path('logout/', logout_page, name='logout-page'),
    path('logout/', MyLogoutView.as_view(), name='logout-page'),
    path('register/', RegisterView.as_view(), name='register-page'),
    path('register/email/', guest_email_view, name='guest-email-view'),
    path('learn_bs/', learn_bootstrap, name='learn-bootstrap'),
    path('success_page/', success_page_view, name='success-page')
)


# urlpatterns = [
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('admin/', admin.site.urls),
#     path('', main_page, name='main-page'),
#     path('api/', include('applications.api.urls')),
#     path('products/', include('applications.products.urls')),
#     path('search/', include('applications.search.urls')),
#     path('cart/', include('applications.cart.urls')),
#     path('addresses/', include('applications.addresses.urls')),
#     path('contacts/', contacts, name='contacts'),
#     path('login/', LoginView.as_view(), name='login-page'),
#     # path('logout/', logout_page, name='logout-page'),
#     path('logout/', MyLogoutView.as_view(), name='logout-page'),
#     path('register/', RegisterView.as_view(), name='register-page'),
#     path('register/email/', guest_email_view, name='guest-email-view'),
#     path('learn_bs/', learn_bootstrap, name='learn-bootstrap'),
#     path('success_page/', success_page_view, name='success-page')
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/products/models.py
import random
import os

from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save
from django.urls import reverse

from supermarket.utils import unique_slug_generator

from applications.categories.models import Category


class InStockManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().exclude(in_stock=False)

    def search(self, query):
        return self.get_queryset().filter(
            Q(title__icontains=query) |
            Q(description__icontains=query) |
            Q(price__icontains=query) |
            Q(tags__title__icontains=query)
        ).distinct().order_by('-id')

    def get_by_slug_name(self, slug):
        return self.get_queryset().get(slug=slug)


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1, 3934343433)
    name, ext = get_filename_ext(filename)
    final_filename = f'{new_filename}{ext}'
    return f'product_images/{new_filename}/{final_filename}'


class Product(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=255, db_index=True)
    description = models.TextField()
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField(default=0)
    in_stock = models.BooleanField(default=True, db_index=True)
    slug = models.SlugField(blank=True, unique=True)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)

    objects = models.Manager()
    instock = InStockManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products:product-slug-detail-cbv', kwargs={'slug': self.slug})


class ProductImage(models.Model):
    image = models.ImageField(upload_to=upload_image_path)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return f'{self.product.title}.jpg'


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

    instance.in_stock = False if instance.quantity == 0 else True


# def product_post_delete_receiver(sender, instance, *args, **kwargs):
#     Product.objects.all().delete()


pre_save.connect(product_pre_save_receiver, sender=Product)
# post_delete.connect(product_post_delete_receiver, sender=Product)

applications/products/forms.py
from django import forms

from .models import Product, ProductImage


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['in_stock', 'slug']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }


class ProductTestForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['in_stock', 'slug']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
        }


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ['image', ]
        widgets = {
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

applications/products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from django.forms import inlineformset_factory

from applications.cart.models import Cart
from applications.products.forms import ProductForm, ProductImageForm, ProductTestForm
from applications.products.models import Product, ProductImage


class ProductList(ListView):
    # queryset = Product.instock.all()
    # queryset = Product.objects.all()
    model = Product
    template_name = 'products/list-cbv.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.instock.all().order_by('-id')
        paginator = Paginator(products, 4)
        page = self.request.GET.get('page')
        context['object_list'] = paginator.get_page(page)
        # context['data'] = [1, 345, 'hello']
        return context


class ProductDetail(DetailView):
    model = Product
    template_name = 'products/detail-cbv.html'


class ProductSlugDetail(DetailView):
    model = Product
    template_name = 'products/detail-slug-cbv.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        request = self.request
        cart_obj, is_new = Cart.objects.get_or_new(request)
        context['cart_obj'] = cart_obj
        return context

def product_list(request):
    products = Product.instock.all().order_by('-id')
    paginator = Paginator(products, 3)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    data = [1, 'asfs', 435.3]
    return render(request, 'products/list.html', locals())


def product_detail(request, id):
    product = get_object_or_404(Product, id=id, in_stock=True)
    return render(request, 'products/detail.html', locals())


def create_product(request):
    form = ProductForm(request.POST or None)
    title = 'Create a product'
    ProductImageFormSet = inlineformset_factory(Product, ProductImage, form=ProductImageForm, extra=1)
    if request.method == 'POST':
        if form.is_valid():
            product = form.save()
            formset = ProductImageFormSet(request.POST, request.FILES, instance=product)
            if formset.is_valid():
                formset.save()
            return redirect(product.get_absolute_url())
    formset = ProductImageFormSet()
    return render(request, 'products/create_product.html', locals())


def update_product(request, id):
    product = get_object_or_404(Product, id=id)
    form = ProductForm(request.POST or None, instance=product)
    title = 'Update a product'
    ProductImageFormSet = inlineformset_factory(Product, ProductImage, form=ProductImageForm, extra=1)
    if request.method == 'POST':
        if form.is_valid():
            product = form.save()
            formset = ProductImageFormSet(request.POST, request.FILES, instance=product)
            if formset.is_valid():
                formset.save()
            return redirect(product.get_absolute_url())
    formset = ProductImageFormSet(instance=product)
    return render(request, 'products/update_product.html', locals())


@require_POST
def delete_product(request, id):
    product = get_object_or_404(Product, id=id)
    product.delete()
    return redirect('products:product-list-cbv')


def create_product_test(request):
    form = ProductTestForm(request.POST or None)
    ProductImageTestFormset = inlineformset_factory(Product, ProductImage, form=ProductImageForm, extra=1)

    if request.method == 'POST':
        if form.is_valid():
            product = form.save()
            formset = ProductImageTestFormset(request.POST, request.FILES, instance=product)
            if formset.is_valid():
                formset.save()
                formset.save()
            return redirect(product.get_absolute_url())
    formset = ProductImageTestFormset()
    return render(request, 'products/create_product_test.html', locals())


def update_product_test(request, id):
    product = get_object_or_404(Product, id=id)
    form = ProductTestForm(request.POST or None, instance=product)

    if request.method == 'POST':
        if form.is_valid():
            product = form.save()
            return redirect(product.get_absolute_url())
    return render(request, 'products/update_product_test.html', locals())


@require_POST
def delete_product_test(request, id):
    product = get_object_or_404(Product, id=id)
    product.delete()
    return redirect(reverse('products:product-list-cbv'))

templates/products/create_product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12 col-sm-10 col-lg-6 d-block mx-auto">
                <h1 class="text-center">{{ title }}</h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <table class="table">
                        {{ formset.management_form }}
                        {{ formset.non_form_errors }}
                        {% for form in formset.forms %}
                            {% if forloop.first %}
                                <thead>
                                <tr>
                                    {% for field in form.visible_fields %}
                                        <th>{{ field.label|capfirst }}</th>
                                    {% endfor %}
                                </tr>
                                </thead>
                            {% endif %}
                            <tr class="formset_row">
                                {% for field in form.visible_fields %}
                                    <td>
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}

                                    {{ field.errors.as_ul }}
                                    {{ field }}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                    <button type="submit" class="btn btn-success d-block mx-auto">Create a product</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.js"></script>
      <script type="text/javascript">
        $('.formset_row').formset({
            addText: '<button class="btn btn-info mt-3">Add new image</button>',
            deleteText: '<button class="btn btn-danger">Delete</button>',
            prefix: 'productimage_set',
        });
    </script>
{% endblock js %}

templates/products/create_product_test.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Создание формы{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12 col-sm-10 col-lg-6 d-block mx-auto">
                <h1 class="text-center">Создание продукта</h1>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <table class="table">
                        {{ formset.management_form }}
                        {{ formset.non_form_errors }}
                        {% for form in formset.forms %}
                            {% if forloop.first %}
                                <thead>
                                <tr>
                                    {% for field in form.visible_fields %}
                                        <th>{{ field.label|capfirst }}</th>
                                    {% endfor %}
                                </tr>
                                </thead>
                            {% endif %}
                            <tr class="formset_row">
                                {% for field in form.visible_fields %}
                                    <td>
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}

                                    {{ field.errors.as_ul }}
                                    {{ field }}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                    <button type="submit" class="btn btn-success d-block mx-auto">Создать продукт</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.js"></script>
      <script type="text/javascript">
        $('.formset_row').formset({
            addText: '<button class="btn btn-info mt-3">Add new image</button>',
            deleteText: '<button class="btn btn-danger">Delete</button>',
            prefix: 'productimage_set',
        });
    </script>
{% endblock js %}

templates/products/delete_product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login Page{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12 col-sm-10 col-lg-6 d-block mx-auto text-center">
                <h1>{{ title }}</h1>
                <form method="post" enctype="multipart/form-data".>
                    {% csrf_token %}
                    {{ form.as_p }}
                    {{ formset.management_form }}
                    {{ formset.non_form_errors }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% endfor %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}{% endblock js %}

templates/products/detail-cbv.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Products detail{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
    <div class="container">
      <div class="row">
          <div class="col-12">
              <h1 class="text-center mt-5">Products detail</h1>
          </div>
      </div>
      <div class="row">
          <div class="col-12 col-md-4 mx-auto d-block text-center mt-5">
              <h4>{{ object.title }}</h4>
              <p>{{ object.description }}</p>
              <p><b>{{ object.price }} сом</b></p>
              {% for image in product.productimage_set.all %}
                <img src="{{ image.image.url }}" height="100px" width="auto"/>
              {% empty %}
                  <p>Нет фотографий</p>
              {% endfor %}
          </div>
      </div>
  </div>
{% endblock content %}
{% block js %}{% endblock js %}

templates/products/detail-slug-cbv.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Products detail{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
    <div class="container">
      <div class="row">
          <div class="col-12">
              <h1 class="text-center mt-5">Products detail</h1>
          </div>
      </div>
         <div class="row">
            <div class="col-12 d-block mx-auto text-center pt-3">
                <form method="post" action="{% url 'products:delete_product' product.id %}" class="mt-3">
                    {% csrf_token %}
                    <a href="{% url 'products:update_product' product.id %}" class="btn btn-info">Update the product</a>
                    <button class="btn btn-danger">Delete the product</button>
                </form>
            </div>
        </div>
      <div class="row">
          <div class="col-12 col-md-10 mx-auto d-block mt-3 text-center">
              <h4 class="mb-3">{{ object.title }}</h4>
                    <div class="row">
                    <div class="col-md-6">
                    <p>{{ object.description }}</p>
                    </div>
                    <div class="col-md-6">
                      <p>Стоимость: <b>{{ object.price }} сом</b></p>
                      <p>Количество: <b>{{ object.quantity }} кг</b></p>
                    </div>
                </div>
                <div class="row mt-3">

                  {% for image in product.productimage_set.all %}
                        <div class="{% if product.productimage_set.count == 1 %}col-12{% elif product.productimage_set.count == 2 %}col-md-6{% elif product.productimage_set.count >= 3 %}col-md-4{% endif %}">
                      <img src="{{ image.image.url }}" height="100px" width="auto"/>
                        </div>
                  {% empty %}
                    </div>

                      <p>Нет фотографий</p>
                  {% endfor %}
          </div>
      </div>
  </div>

  <div class="container mt-5">
    <div class="row">
      <div class="col-12 d-block mx-auto text-center">
          {% include 'snippets/cart-update.html' with product=object %}
      </div>
    </div>
  </div>

{% endblock content %}
{% block js %}{% endblock js %}

templates/products/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Products detail{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
    <div class="container">
      <div class="row">
          <div class="col-12">
              <h1 class="text-center mt-5">Products detail</h1>
          </div>
      </div>
      <div class="row">
          <div class="col-12 col-md-4 mx-auto d-block text-center mt-5">
              <h4>{{ product.title }}</h4>
              <p>{{ product.description }}</p>
              <p><b>{{ product.price }} сом</b></p>
              {% for image in product.productimage_set.all %}
                <img src="{{ image.image.url }}" height="100px" width="auto"/>
              {% empty %}
                  <p>Нет фотографий</p>
              {% endfor %}
          </div>
      </div>
  </div>
{% endblock content %}
{% block js %}{% endblock js %}

templates/products/list-cbv.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Products list{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1 class="text-center mt-5">Products list</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-12 text-center mt-3">
        <a href="{% url 'products:create_product' %}" class="btn btn-success">Add new product</a>
      </div>
    </div>
    <div class="row">
      {% for object in object_list %}
        {% include 'includes/cart.html' with product=object %}
      {% empty %}
      {% endfor %}
    </div>
  </div>
  <div class="container mb-3">
    <div class="row">
      <div class="col-12 col-sm-10 col-md-8 col-lg-6 mx-auto d-block text-center">
        <div class="pagination mx-auto d-block">
                    <span class="step-links">
                        {% if object_list.has_previous %}
                          <a href="?page=1">&laquo; first</a>
                          <a href="?page={{ object_list.previous_page_number }}">previous</a>
                        {% endif %}

                      <span class="current">
                            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
                        </span>

                      {% if object_list.has_next %}
                        <a href="?page={{ object_list.next_page_number }}">next</a>
                        <a href="?page={{ object_list.paginator.num_pages }}">last &raquo;</a>
                      {% endif %}
                    </span>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}
{% block js %}{% endblock js %}

templates/products/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Products list{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
     <div class="container">
      <div class="row">
          <div class="col-12">
              <h1 class="text-center mt-5">Products list</h1>
          </div>
      </div>
      <div class="row">
          {% for product in products %}
              <div class="col-12 mx-auto d-block text-center mt-5">
                  <hr>
                  <a href="{% url 'products:product-detail' product.id %}">{{ product.title }}</a>
                  <p>{{ product.description }}</p>
                    {% if product.productimage_set.first %}
                        <img src="{{ product.productimage_set.first.image.url }}" height="100px" width="auto"/>
                    {% else %}
                      <p>Нет фотографии</p>
                    {% endif %}
                  <hr>
              </div>
          {% empty %}
          {% endfor %}
      </div>
  </div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-10 col-md-8 col-lg-6 mx-auto d-block text-center">
                <div class="pagination">
                    <span class="step-links">
                        {% if products.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ products.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ products.number }} of {{ products.paginator.num_pages }}.
                        </span>

                        {% if products.has_next %}
                            <a href="?page={{ products.next_page_number }}">next</a>
                            <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}{% endblock js %}

templates/products/update_product.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ title }}{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12 col-sm-10 col-lg-6 d-block mx-auto">
                <h1 class="text-center">{{ title }}</h1>
                <form method="post" enctype="multipart/form-data".>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <table class="table">
                        {{ formset.management_form }}
                        {{ formset.non_form_errors }}
                        {% for form in formset.forms %}
                            {% if forloop.first %}
                                <thead>
                                <tr>
                                    {% for field in form.visible_fields %}
                                        <th>{{ field.label|capfirst }}</th>
                                    {% endfor %}
                                </tr>
                                </thead>
                            {% endif %}
                            <tr class="formset_row">
                                {% for field in form.visible_fields %}
                                    <td>
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}

                                    {{ field.errors.as_ul }}
                                    {{ field }}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                    <button type="submit" class="btn btn-success d-block mx-auto">Update the product</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.js"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            addText: '<button class="btn btn-info mt-3">Add new image</button>',
            deleteText: '<button class="btn btn-danger">Delete</button>',
            prefix: 'productimage_set',
        });
    </script>
{% endblock js %}

templates/products/update_product_test.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Изменение продукта{% endblock title %}
{% block css %}{% endblock css %}
{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12 col-sm-10 col-lg-6 d-block mx-auto">
                <h1 class="text-center">Изменение продукта</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success d-block mx-auto">Update the product</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}
{% block js %}
{% endblock js %}