applications/cart/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from applications.orders import views as order_views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart-page'),
    path('update/', views.cart_update, name='update'),
    path('checkout/', order_views.checkout_page, name='checkout'),
]

applications/search/urls.py
from django.urls import path
from .views import SearchView

app_name = 'search'
urlpatterns = [
    path('', SearchView.as_view(), name='search-page'),
]

supermarket/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from applications.accounts.views import (
    LoginView,
    MyLogoutView,
    RegisterView,
    guest_email_view,
)
from .views import (
    main_page,
    contacts,
    learn_bootstrap,
)

from applications.orders.views import success_page_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    path('', main_page, name='main-page'),
    path('api/', include('applications.api.urls')),
    path('products/', include('applications.products.urls')),
    path('search/', include('applications.search.urls')),
    path('cart/', include('applications.cart.urls')),
    path('addresses/', include('applications.addresses.urls')),
    path('contacts/', contacts, name='contacts'),
    path('login/', LoginView.as_view(), name='login-page'),
    # path('logout/', logout_page, name='logout-page'),
    path('logout/', MyLogoutView.as_view(), name='logout-page'),
    path('register/', RegisterView.as_view(), name='register-page'),
    path('register/email/', guest_email_view, name='guest-email-view'),
    path('learn_bs/', learn_bootstrap, name='learn-bootstrap'),
    path('success_page/', success_page_view, name='success-page')
)


# urlpatterns = [
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('admin/', admin.site.urls),
#     path('', main_page, name='main-page'),
#     path('api/', include('applications.api.urls')),
#     path('products/', include('applications.products.urls')),
#     path('search/', include('applications.search.urls')),
#     path('cart/', include('applications.cart.urls')),
#     path('addresses/', include('applications.addresses.urls')),
#     path('contacts/', contacts, name='contacts'),
#     path('login/', LoginView.as_view(), name='login-page'),
#     # path('logout/', logout_page, name='logout-page'),
#     path('logout/', MyLogoutView.as_view(), name='logout-page'),
#     path('register/', RegisterView.as_view(), name='register-page'),
#     path('register/email/', guest_email_view, name='guest-email-view'),
#     path('learn_bs/', learn_bootstrap, name='learn-bootstrap'),
#     path('success_page/', success_page_view, name='success-page')
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/cart-update.html
<form method="post" action="{% url 'cart:update' %}">
  {% csrf_token %}
  <input type="hidden" name="product_id" value="{{ product.id }}"/>

  {% if in_cart %}
    <button type="submit" class="mt-3 btn btn-danger">Удалить</button>
  {% else %}
    {% if product not in cart_obj.products.all %}
      <b>Товара нет в корзине.
        <br>
        Не хотели бы вы его добавить?</b>
      <br>
      <button type="submit" class="mt-3 btn btn-success">Добавить</button>
    {% else %}
      <b>Товар есть в корзине.
        <br>
        Не хотели бы вы его удалить?</b>
      <br>
      <button type="submit" class="mt-3 btn btn-danger">Удалить</button>
    {% endif %}
  {% endif %}
</form>

templates/snippets/search_block.html
<form class="form-inline" method="get" action="{% url 'search:search-page' %}">
  <input name="q" class="form-control font-weight-bold" type="search" placeholder="Search" {% if request.GET.q %}value="{{ request.GET.q }}"{% endif %}>
  <button class="btn btn-danger font-weight-bold" type="submit">Search</button>
</form>