applications/cart/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views
from applications.orders import views as order_views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart-page'),
    path('update/', views.cart_update, name='update'),
    path('checkout/', order_views.checkout_page, name='checkout'),
]

applications/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.product_list, name='product-list'),
    path('cbv/', views.ProductList.as_view(), name='product-list-cbv'),
    path('cbv/<str:slug>/', views.ProductSlugDetail.as_view(), name='product-slug-detail-cbv'),
    path('<int:id>/', views.product_detail, name='product-detail'),
    path('<int:pk>/cbv/', views.ProductDetail.as_view(), name='product-detail-cbv'),
    path('create/', views.create_product, name='create_product'),
    path('create_product/', views.create_product_test, name='create_product_test'),
    path('update/<int:id>/', views.update_product, name='update_product'),
    path('update_product/<int:id>/', views.update_product_test, name='update_product_test'),
    path('delete/<int:id>/', views.delete_product, name='delete_product'),
    path('delete_product/<int:id>/', views.delete_product_test, name='delete_product_test'),
]

supermarket/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from applications.accounts.views import (
    LoginView,
    MyLogoutView,
    RegisterView,
    guest_email_view,
)
from .views import (
    main_page,
    contacts,
    learn_bootstrap,
)

from applications.orders.views import success_page_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    path('', main_page, name='main-page'),
    path('api/', include('applications.api.urls')),
    path('products/', include('applications.products.urls')),
    path('search/', include('applications.search.urls')),
    path('cart/', include('applications.cart.urls')),
    path('addresses/', include('applications.addresses.urls')),
    path('contacts/', contacts, name='contacts'),
    path('login/', LoginView.as_view(), name='login-page'),
    # path('logout/', logout_page, name='logout-page'),
    path('logout/', MyLogoutView.as_view(), name='logout-page'),
    path('register/', RegisterView.as_view(), name='register-page'),
    path('register/email/', guest_email_view, name='guest-email-view'),
    path('learn_bs/', learn_bootstrap, name='learn-bootstrap'),
    path('success_page/', success_page_view, name='success-page')
)


# urlpatterns = [
#     path('i18n/', include('django.conf.urls.i18n')),
#     path('admin/', admin.site.urls),
#     path('', main_page, name='main-page'),
#     path('api/', include('applications.api.urls')),
#     path('products/', include('applications.products.urls')),
#     path('search/', include('applications.search.urls')),
#     path('cart/', include('applications.cart.urls')),
#     path('addresses/', include('applications.addresses.urls')),
#     path('contacts/', contacts, name='contacts'),
#     path('login/', LoginView.as_view(), name='login-page'),
#     # path('logout/', logout_page, name='logout-page'),
#     path('logout/', MyLogoutView.as_view(), name='logout-page'),
#     path('register/', RegisterView.as_view(), name='register-page'),
#     path('register/email/', guest_email_view, name='guest-email-view'),
#     path('learn_bs/', learn_bootstrap, name='learn-bootstrap'),
#     path('success_page/', success_page_view, name='success-page')
# ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>
    {% block title %}{% endblock title %}
  </title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  {% block css %}{% endblock css %}
</head>
<body>

<nav class="navbar navbar-expand-lg bg-dark bg-light px-sm-5">
  <a class="navbar-brand text-white font-weight-bold" href="#">ФРУНЗЕ</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse font-weight-bold" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'main-page' %}">{% trans 'Main Page' %}<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'contacts' %}">{% trans 'Contacts' %} <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-white" href="{% url 'products:product-list-cbv' %}">{% trans 'Products' %}<span class="sr-only">(current)</span></a>
      </li>
      {% if not request.user.is_authenticated %}
        <li class="nav-item text-white">
          <a class="nav-link text-white" href="{% url 'login-page' %}">{% trans 'Login' %}<span class="sr-only">(current)</span></a>
        </li>
        <li>
          <a class="nav-link text-white" href="{% url 'register-page' %}">{% trans 'Register' %}</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'logout-page' %}">{% trans 'Logout' %}<span class="sr-only">(current)</span></a>
        </li>
      {% endif %}
        <li>
          <a class="nav-link text-white" href="{% url 'cart:cart-page' %}">
            <i class="fab fa-opencart" style="font-size: 25px">
              {% if request.session.cart_items %}<span class="bg-danger" style="padding: 5px 10px; border-radius: 100%">{{ request.session.cart_items }}</span>{% endif %}
            </i>
          </a>
        </li>
        <li>
          <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}" >
            <select name="language">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
                <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                  {{ language.name_local }} ({{ language.code }})
                </option>
              {% endfor %}
            </select>
            <input type="submit" value="Go" />
          </form>
        </li>
    </ul>
  {% include 'snippets/search_block.html' %}
  </div>
</nav>
{% block content %}{% endblock content %}
<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/infinite.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
{% block js %}{% endblock js %}
</body>
</html>

templates/bootstrap-learn.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Hello, Miami!{% endblock title %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
{% endblock css %}
{% block content %}
        <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown button
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="#">Action</a>
    <a class="dropdown-item" href="#">Another action</a>
    <a class="dropdown-item" href="#">Something else here</a>
  </div>
</div>
                <div class="container bg-primary">
                <div class="alert alert-primary" role="alert">
                  This is a primary alert—check it out!
                </div>
            </div>
            <div class="container-fluid bg-danger">
                <div class="alert alert-success" role="alert">
                  This is a primary alert—check it out!
                </div>
            </div>
    <div class="container-fluid bg-dark">
        <div class="row">
            <div class="d-block mx-auto col-12 col-sm-10 col-lg-8">
                <h1 class="text-center mt-5 text-warning">
                    Hello, {% if request.user.is_authenticated %}{{ request.user.username|title }}{% else %}Miami{% endif %}!
                </h1>
            </div>
        </div>
        <div class="row text-white">
            <div class="col-12 col-sm-6 col-md-6 col-lg-8 col-xl bg-warning">Hello</div>
            <div class="col-12 col-sm col-md-6 col-lg-4 col-xl bg-danger">Hello</div>
            <div class="col-12 col-sm col-md-12 col-lg-6 col-xl bg-success">Hello</div>
        </div>
        <div class="row text-white">
            <div class="col-12 col-sm-6 col-md-6 col-lg-8 col-xl bg-primary">Hello</div>
            <div class="col-12 col-sm col-md-6 col-lg-4 col-xl bg-info">Hello</div>
            <div class="col-12 col-sm col-md-12 col-lg-6 col-xl bg-danger">Hello</div>
        </div>
    </div>
    <div class="container p-5">
        <div class="row text-center">
            <div class="col-6 offset-3">
                <div class="alert alert-primary" role="alert">
                  This is a primary alert—check it out!
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col text-center">
                <button type="button" class="btn btn-outline-danger">Secondary</button>
            </div>
            <div class="col text-center">
                <button type="button" class="btn btn-outline-success btn-lg ">Success</button>
            </div>
        </div>
        <div class="row">
            <div class="col-6 offset-3 text-center">
                <div class="btn-group" role="group" aria-label="Basic example">
                  <button type="button" class="btn btn-secondary">Left</button>
                  <button type="button" class="btn btn-secondary">Middle</button>
                  <button type="button" class="btn btn-secondary">Right</button>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-4 mt-5">
                <div class="card" style="width: 18rem;">
                  <img class="card-img-top" src="{% static 'images/background/maiami.jpg' %}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
            </div>
            <div class="col-4 mt-5">
                <div class="card" style="width: 18rem;">
                  <img class="card-img-top" src="{% static 'images/background/maiami.jpg' %}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
            </div>
            <div class="col-4 mt-5">
                <div class="card" style="width: 18rem;">
                  <img class="card-img-top" src="{% static 'images/background/maiami.jpg' %}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
            </div>
            <div class="col-4 mt-5">
                <div class="card" style="width: 18rem;">
                  <img class="card-img-top" src="{% static 'images/background/maiami.jpg' %}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
            </div>
            <div class="col-4 mt-5">
                <div class="card" style="width: 18rem;">
                  <img class="card-img-top" src="{% static 'images/background/maiami.jpg' %}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
            </div>
            <div class="col-4 mt-5">
                <div class="card" style="width: 18rem;">
                  <img class="card-img-top" src="{% static 'images/background/maiami.jpg' %}" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt-5">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'images/background/maiami.jpg' %}" alt="First slide">
        <div class="carousel-caption d-none d-md-block">
            <h5>Django</h5>
            <p>I love Python</p>
          </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'images/background/maiami.jpg' %}" alt="Second slide">
        <div class="carousel-caption d-none d-md-block">
            <h5>Django</h5>
            <p>I love Python</p>
          </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'images/background/maiami.jpg' %}" alt="Third slide">
        <div class="carousel-caption d-none d-md-block">
            <h5>Django</h5>
            <p>I love Python</p>
          </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
    </div>

    <div class="container mt-5">
        <div class="row">
            <div class="col-8 offset-2">
                <form>
  <div class="form-row">
    <div class="col-md-4 mb-3">
      <label for="validationServer01">First name</label>
      <input type="text" class="form-control is-valid" id="validationServer01" placeholder="First name" value="Mark" required>
      <div class="valid-feedback">
        Looks good!
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <label for="validationServer02">Last name</label>
      <input type="text" class="form-control is-valid" id="validationServer02" placeholder="Last name" value="Otto" required>
      <div class="valid-feedback">
        Looks good!
      </div>
    </div>
    <div class="col-md-4 mb-3">
      <label for="validationServerUsername">Username</label>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupPrepend3">@</span>
        </div>
        <input type="text" class="form-control is-invalid" id="validationServerUsername" placeholder="Username" aria-describedby="inputGroupPrepend3" required>
        <div class="invalid-feedback">
          Please choose a username.
        </div>
      </div>
    </div>
  </div>
  <div class="form-row">
    <div class="col-md-6 mb-3">
      <label for="validationServer03">City</label>
      <input type="text" class="form-control is-invalid" id="validationServer03" placeholder="City" required>
      <div class="invalid-feedback">
        Please provide a valid city.
      </div>
    </div>
    <div class="col-md-3 mb-3">
      <label for="validationServer04">State</label>
      <input type="text" class="form-control is-invalid" id="validationServer04" placeholder="State" required>
      <div class="invalid-feedback">
        Please provide a valid state.
      </div>
    </div>
    <div class="col-md-3 mb-3">
      <label for="validationServer05">Zip</label>
      <input type="text" class="form-control is-invalid" id="validationServer05" placeholder="Zip" required>
      <div class="invalid-feedback">
        Please provide a valid zip.
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="form-check">
      <input class="form-check-input is-invalid" type="checkbox" value="" id="invalidCheck3" required>
      <label class="form-check-label" for="invalidCheck3">
        Agree to terms and conditions
      </label>
      <div class="invalid-feedback">
        You must agree before submitting.
      </div>
    </div>
  </div>
  <button class="btn btn-primary" type="submit">Submit form</button>
</form>
            </div>
        </div>
    </div>

{% endblock content %}
{% block js %}
<!--    <script>
        alert('Hello world!');
    </script> -->
{% endblock js %}

templates/contacts.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}Contacts{% endblock title %}
    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-10 col-md-8 col-lg-6 col-xl-4 d-block mx-auto">
                    <h1 class="text-center mt-5">Contacts</h1>
                    <form method="POST" class="d-block mx-auto text-center">
                        {% csrf_token %}
                        <!--{{ contacts_form.as_ul }}-->
                        {{ contacts_form.non_field_errors }}
                        <div class="form-group">
                            {{ contacts_form.name.errors }}
                            {{ contacts_form.name }}
                        </div>
                        <div class="form-group">
                            {{ contacts_form.email.errors }}
                            {{ contacts_form.email }}
                        </div>
                        <div class="form-group">
                            {{ contacts_form.message.errors }}
                            {{ contacts_form.message }}
                        </div>
                        <button type="submit" class="btn btn-success">Отправить</button>
                    </form>
                </div>
            </div>
        </div>


            <!--<form method="POST" class="mt-5 d-block mx-auto text-center">
                <input type="text" class="form-control" placeholder="Имя" name="name"/>
                <input type="email" class="form-control" placeholder="Email" name="email"/>
                <textarea></textarea>
                <button type="submit" class="btn btn-success">Отправить</button>
            </form>-->
    {% endblock content %}
    {% block js %}{% endblock js %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
{% load thumbnail %}
{% block title %}Hello, Miami!{% endblock title %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
{% endblock css %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="d-none d-sm-none d-md-block col-md-3">
                <ul class="list-group">
                    {% for c in categories %}
                    <li class="list-group-item"><a href="#">{{ c.title }}</a></li>
                    {% empty %}
                    <li class="list-group-item">Нет категорий</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-12 col-md-9 p-0 mx-0">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{% static 'images/background/maiami.jpg' %}" alt="First slide">
        <div class="carousel-caption d-none d-md-block">
            <h5>Django</h5>
            <p>I love Python</p>
          </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'images/background/maiami.jpg' %}" alt="Second slide">
        <div class="carousel-caption d-none d-md-block">
            <h5>Django</h5>
            <p>I love Python</p>
          </div>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{% static 'images/background/maiami.jpg' %}" alt="Third slide">
        <div class="carousel-caption d-none d-md-block">
            <h5>Django</h5>
            <p>I love Python</p>
          </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
            </div>
        </div>
    </div>

{#    <div class="container">#}
{#      <div class="row">#}
{#        <div class="col-12" class="d-block mx-auto text-center">#}
{#          {% for category in categories_list %}#}
{#              {{ category.title }}#}
{#          {% empty %}#}
{#              No categories#}
{#          {% endfor %}#}
{#          <form method="post" enctype="multipart/form-data" action="{% url 'products:create_product' %}">#}
{#                    {% csrf_token %}#}
{#                    {{ form.as_p }}#}
{#                    <table class="table">#}
{#                        {{ formset.management_form }}#}
{#                        {{ formset.non_form_errors }}#}
{#                        {% for form in formset.forms %}#}
{#                            {% if forloop.first %}#}
{#                                <thead>#}
{#                                <tr>#}
{#                                    {% for field in form.visible_fields %}#}
{#                                        <th>{{ field.label|capfirst }}</th>#}
{#                                    {% endfor %}#}
{#                                </tr>#}
{#                                </thead>#}
{#                            {% endif %}#}
{#                            <tr class="formset_row">#}
{#                                {% for field in form.visible_fields %}#}
{#                                    <td>#}
{#                                    {% if forloop.first %}#}
{#                                        {% for hidden in form.hidden_fields %}#}
{#                                            {{ hidden }}#}
{#                                        {% endfor %}#}
{#                                    {% endif %}#}
{##}
{#                                    {{ field.errors.as_ul }}#}
{#                                    {{ field }}#}
{#                                    </td>#}
{#                                {% endfor %}#}
{#                            </tr>#}
{#                        {% endfor %}#}
{#                    </table>#}
{#                    <button type="submit" class="btn btn-success d-block mx-auto">Create a product</button>#}
{#                </form>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}

    <div class="container">
        <div class="row infinite-container">
            {% for product in products %}
            <div class="col-12 col-sm-6 col-md-4 my-5 infinite-item">
                <div class="card d-block mx-auto text-center py-5" style="width: 18rem;">
                    {% if product.productimage_set.first %}
                      {% thumbnail product.productimage_set.first.image 150x150 crop as thumb %}
                        <img  alt="супермаркет ФРУНЗЕ" src="{{ thumb.url }}"/>
                    {% else %}
                      <p>Нет фотографии</p>
                    {% endif %}
                  <div class="card-body">
                    <h5 class="card-title">{% upper_string product.title %}</h5>
                    <p class="card-text">{{ product.description|truncatewords:1 }}</p>
                    <a href="{{ product.get_absolute_url }}" class="btn btn-primary">Посмотреть</a>
                  </div>
                </div>
            </div>
        {% empty %}
        <h5>Нет продуктов</h5>
        {% endfor %}
        </div>
        <div class="row">
            <div class="col-12">
                 {% if products.has_next %}
                    <a class="infinite-more-link" href="?page={{ products.next_page_number }}">More</a>
                  {% endif %}
            </div>
        </div>
    </div>
    <!--<div class="container-fluid">
        <div class="loading alert alert-danger" role="alert">
        This is a danger alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
        </div>
    </div>-->
{% endblock content %}
{% block js %}
    <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
/*      onBeforePageLoad: function () {
        $('.loading').show();
      },
      onAfterPageLoad: function ($items) {
        $('.loading').hide();
      } */
    });
  </script>
{% endblock js %}